### ISSUE TITLE
Morning session: Peer to Peer Code Review

### ISSUE THREAD

**Issue by Bennyjoez** [prius2055/JavaScript-capstone-project#23]
### Peer To Peer Code Review.
Hello, @JOdiemo @prius2055, 👋🏾 
You guys have done a really good job, in implementing the Kanban and setting up the project. 
However, I have one suggestion: 
- Kindly link the `issues` to the respective `pull request` that is aimed at fixing/solving the `issue`. This ensures that an issue is closed when it's pull request is merged. 
> Good Luck 😄

**Comment by JOdiemo** [comment]
Understood how to link the issue to the pull request. 
![image](https://user-images.githubusercontent.com/94829275/232707172-753ad2d6-8aa2-4b45-a475-b9ffc73bacbd.png)

**Comment by JOdiemo** [comment]
Thanks to my morning session team for the empowerment
